---
- include: preflight.yml
  tags:
    - vmagent_configure
    - vmagent_install
    - vmagent_run

- include: install.yml
  become: true
  tags:
    - vmagent_install

- include: configure.yml
  become: true
  tags:
    - vmagent_configure

- name: ensure vmagent service is started and enabled
  become: true
  systemd:
    daemon_reload: true
    name: vmagent
    state: started
    enabled: true
  tags:
    - vmagent_run
