---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    vmagent_systemd_version: "{{ __systemd_version.stdout_lines[0].split(' ')[-1] }}"

- block:
    - name: "Get checksum list"
      set_fact:
        __vmagent_checksums: "{{ lookup('url', 'https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v' + vmagent_version + '/vmutils-v' + vmagent_version + '_checksums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum"
      set_fact:
        __vmagent_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ __vmagent_checksums }}"
  delegate_to: localhost
  when:
    - not vmagent_skip_install
